version: 2
jobs:
  build:
    docker:
    - image: circleci/php:latest
    steps:
    - checkout
    - run: sudo apt install -y libsqlite3-dev zlib1g-dev
    - run: sudo docker-php-ext-install zip
    - run: sudo docker-php-ext-install gd
    - run: sudo docker-php-ext-install bcmath
    - run: sudo composer self-update
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
        - vendor
    - run: cp .env.example .env
    - run: php artisan key:generate
    - run: ./vendor/bin/phpunit
workflows:
  version: 2
  workflow:
    jobs:
    - build